#spring.kafka.bootstrap-servers=kafka:9092
#spring.kafka.bootstrap-servers=host.docker.internal:9092
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL}
topic.name=${ORDER_TOPIC_NAME}
kafka.dlq.topic=${ORDER_DLQ_TOPIC_NAME}

